---
title: Sawyer Hollenshead
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    external_link: 
    dates: 
    section: featured
url: http://www.sawyerh.com
sass:
  style: compressed
permalink: "/writing/:title/"
markdown: redcarpet
exclude:
- README.md
- ".gitignore"
- node_modules/
- bower_components/
- package.json
- webpack.config.js
footer_content: Built on [Jekyll](http://jekyllrb.com/). Managed with [Siteleaf](http://siteleaf.com).
  Hosted on [AWS](http://aws.amazon.com). Soleil typeface by [Type Together](http://www.type-together.com/)
  and served via [Typekit](http://typekit.com). Icon font by [Symbolset](http://symbolset.com).
  Designed in [Sketch](https://www.sketchapp.com/). Written in [Sublime Text](http://www.sublimetext.com/).
  Built in [NYC](https://media.giphy.com/media/7mUhYZhzb8AM/giphy.gif) listening to
  [tunes](https://open.spotify.com/user/1247662653/playlist/668ohC3PIIyIyj1g8R7nQu).
google_analytics: 3634425-8
gems:
- jekyll-sitemap
