---
title: Sawyer Hollenshead
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    external_link: ''
    dates: ''
sass:
  style: compressed
permalink: "/writing/:title/"
markdown: redcarpet
exclude:
- Copywriting.md
- README.md
- tmp
- ".gitignore"
- node_modules/
- bower_components/
- package.json
- webpack.config.js
footer_content: Content managed with [Siteleaf](http://siteleaf.com). Site hosted
  on [AWS](http://aws.amazon.com). Europa typeface hosted by [Typekit](http://typekit.com).
  Icon font by [Symbolset](http://symbolset.com). Designed in [Sketch](https://www.sketchapp.com/).
  Written in [Sublime Text 3](http://www.sublimetext.com/). Built in [NYC](https://media.giphy.com/media/7mUhYZhzb8AM/giphy.gif).
google_analytics: 3634425-8
gems:
- jekyll-sitemap
- jekyll-feed
